# Generated by Django 5.2.17 on 2026-08-22 10:27

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
    ]
