# Generated by Django 5.2.17 on 2026-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_booking_hotels_book_room_id_2bee67_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_args', models.TextField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
