# Generated by Django 5.2.17 on 2026-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_failedtasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
