# Generated by Django 5.2.17 on 2026-08-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ai_description',
            field=models.TextField(blank=True),
        ),
    ]
