# Generated by Django 5.2.17 on 2026-08-26 11:23

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_property_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='review_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
